server.port=${PORT:8080}
youtube.api.key=${YOUTUBE_API_KEY}
python.service.url=${PYTHON_SERVICE_URL:http://localhost:8000/predictSentiment}
python.service.url.detailed=${PYTHON_SERVICE_URL_DETAILED:http://localhost:8000/analyzeDetailed}
python.service.url.learnmore=${PYTHON_SERVICE_URL_LEARNMORE:http://localhost:8000/learnMore}
gemini.api.key=${GEMINI_API_KEY}
wikipedia.api.url=${WIKIPEDIA_API_URL:https://en.wikipedia.org/api/rest_v1/page/summary/}

